name: Documentation Update
description: Request improvements or fixes to documentation
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear docs make the ASO skill more accessible to everyone.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - README.md
        - CLAUDE.md (project instructions)
        - GitHub Wiki
        - API documentation (function docstrings)
        - Installation guide
        - Usage examples
        - README.md (skill)
        - CHANGELOG.md
        - Code comments
        - Error messages
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What's wrong with the current documentation?
      options:
        - Inaccurate information
        - Missing information
        - Unclear explanation
        - Outdated content
        - Broken links
        - Typo or formatting
        - Missing examples
        - Needs more detail
        - Too complex (needs simplification)
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (paste relevant section or provide link)
      placeholder: |
        Current section (README.md line 45):
        "Install the ASO skill by copying the folder to your Claude installation"
    validations:
      required: true

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed Improvement
      description: What should it say instead? Provide your suggested wording
      placeholder: |
        Suggested improvement:
        "Install the ASO skill:
        ```bash
        cp -r app-store-optimization ~/.claude/skills/
        ```
        Verify installation:
        ```bash
        ls ~/.claude/skills/app-store-optimization/
        # Should show: SKILL.md, 8 Python modules, sample files
        ```"
    validations:
      required: true

  - type: dropdown
    id: aso-relevance
    attributes:
      label: ASO Skill Relevance
      description: Is this specific to ASO functionality?
      options:
        - Yes - ASO-specific (character limits, metadata, keywords)
        - No - General documentation (installation, usage, setup)
        - Both
    validations:
      required: false

  - type: textarea
    id: affected-users
    attributes:
      label: Who Is Affected?
      description: Which users would benefit from this documentation update?
      placeholder: |
        Example: New users installing the skill for the first time struggle with this step
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context (screenshots, related issues, external references)
      placeholder: |
        - Related to issue #123
        - Screenshot: [attach]
        - External reference: https://docs.example.com/best-practices
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have checked the current documentation is indeed inaccurate/incomplete
          required: true
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a specific proposed improvement
          required: true
